### ISSUE TITLE
Md5sum

### ISSUE THREAD

**Issue by vibhoothi** [Telecommunication-Telemedia-Assessment/AVT-VQDB-UHD-2-HDR#1]
Can we get md5sum of all the mkv files, as it is very large, hash values will be highly desirable to be sure we have right file:)

**Comment by stg7** [comment]
checksums are on the way, they will be found here: https://avtshare01.rz.tu-ilmenau.de/avt-vqdb-uhd-2-hdr/checksums.sha512 and https://avtshare01.rz.tu-ilmenau.de/avt-vqdb-uhd-2-hdr/checksums.md5

processing will maybe take a day.

@Weiver23 , soon to be checked by an additional pair of :eye: :eye:

**Comment by stg7** [comment]
@Weiver23 we should link and mention the checksums in the readme

**Comment by Weiver23** [comment]
> @Weiver23 we should link and mention the checksums in the readme

done
