### ISSUE TITLE
Wrong filename for 6_Conversatiion_Standing.mkv

### ISSUE THREAD

**Issue by vibhoothi** [Telecommunication-Telemedia-Assessment/AVT-VQDB-UHD-2-HDR#2]
The 6_Conversatiion_Standing.mkv is having extra i, while as per https://github.com/Telecommunication-Telemedia-Assessment/AVT-VQDB-UHD-2-HDR/blob/main/download.sh#L11, it shouldn't be,

Would be good if we can get the filename in the server fixed before it is too late

https://avtshare01.rz.tu-ilmenau.de/avt-vqdb-uhd-2-hdr/6_Conversatiion_Standing.mkv

**Comment by stg7** [comment]
we fixed the filename issue, @Weiver23  will check it two more :eye: :eye:   :)

**Comment by Weiver23** [comment]
> The 6_Conversatiion_Standing.mkv is having extra i, while as per https://github.com/Telecommunication-Telemedia-Assessment/AVT-VQDB-UHD-2-HDR/blob/main/download.sh#L11, it shouldn't be,
> 
> Would be good if we can get the filename in the server fixed before it is too late
> 
> https://avtshare01.rz.tu-ilmenau.de/avt-vqdb-uhd-2-hdr/6_Conversatiion_Standing.mkv

thanks for mentioning it! 
thanks @stg7 for fixing it :)
